### PR TITLE
fix(stylelint): remove unknow stylelint rule

### PR DESCRIPTION
**Pull request by rands0n**
This is related to this PR https://github.com/primer/buttons/pull/1

### CODE REVIEW

**Comment by ntwb** [comment]
As part of stylelint 7.0: https://github.com/stylelint/stylelint/releases/tag/7.0.0

> Removed: `media-query-parentheses-space-inside` rule. Use the new `media-feature-parentheses-space-inside` rule instead.

@rands0n Check your stylelint version, either your local or global version I expect is out of date:

```shell
stylelint --version
./node_modules/.bin/stylelint --version
```

**Comment by rands0n** [comment]
@ntwb I use the local module installed by buttons primer. Which in this case is `6.9.0`. Hence the errors there fail because he gets here. Which the version of here is 7.

I think just change the rule is enough? Agree with me?

**Comment by ntwb** [comment]
> Agree with me?

No, this repo `stylelint-config-primer` has been updated to use the 7.x branch of stylelint

The `buttons` repo should be updated to stylelint 7.x, see https://github.com/primer/buttons/pull/1#issuecomment-233146806,

**Comment by jonrohan** [comment]
I started here updating the stylelint version and I'm working on updating
all the modules to 7.0, but got busy this week. Will be getting to it at
the end of the week.

**Pull request closed without merging**
